--THE QUALITY OF THIS TABLE IS GOOD bronze.erp_PX_CAT_G1V2 DIRECT INSERTING 



INSERT INTO silver.erp_PX_CAT_G1V2 
SELECT 
*
FROM bronze.erp_PX_CAT_G1V2


SELECT *

FROM silver.erp_PX_CAT_G1V2 
--GOOD